### ISSUE TITLE
No list displayed anymore

### ISSUE THREAD

**Issue by nin3** [Quitten/Autorize#54] opened 2020-07-05 13:44 UTC
The request lists isn't displayed anymore for some reason, it's empty.
I was working with Autorize without issues, I don't know what happend if at all.

**Comment by Quitten** [comment] 2020-07-05 14:39
@nin3 - can you elaborate? Share a screenshot? did you check error logs?

**Comment by nin3** [comment] 2020-07-05 17:00
@Quitten 

![image](https://user-images.githubusercontent.com/16447307/86537748-1e705080-befa-11ea-910d-0f713efca083.png)

**Comment by nin3** [comment] 2020-07-05 17:32
btw, I've checked in Logger and Logger++ nothing there

**Comment by Quitten** [comment] 2020-07-05 17:41
I noticed you have an interception filter set to scope items only, there is a chance that this is the problem? Can you try deleting it?

**Comment by nin3** [comment] 2020-07-05 17:48
Done, didn't work ;x

**Comment by nin3** [comment] 2020-07-05 18:11
Oh, and I tried in both burp versions - 2.x and 1.76

**Comment by nin3** [comment] 2020-07-07 13:37
Hello Barak,

Any updates?

**Comment by Quitten** [comment] 2020-07-08 09:52
@nin3  - That's sound super weird, and nobody else is complaining for such bugs. Anyway, on which Autorize version it occurs? try to go over the releases and see on which version are you having this issue.
In addition, are you sure you checked Extender -> Errors ?
In case of an error they should pop up there, I would like to have a video or ways to reproduce it because I cannot reproduce.

**Comment by Quitten** [comment] 2020-07-12 11:55
@nin3 - closing until additional information will be provided

**Closed by Quitten** 2020-07-12 11:55 UTC

**Comment by nin3** [comment] 2020-07-12 15:39
@Quitten - something weird happend, I'm not sure why, no errors, but uninstall and install from burp's bapps store fixed the issue :).
Thanks for the help!
Sharon

**Comment by Quitten** [comment] 2020-07-12 17:40
@nin3 - Happy you were manage to solve it :)
Enjoy!
Barak
